//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joomiz.Blog.Domain.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Joomiz.Blog.Domain.Validation.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address is invalid..
        /// </summary>
        internal static string AuthorEmailAddressIsInvalid {
            get {
                return ResourceManager.GetString("AuthorEmailAddressIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address is required..
        /// </summary>
        internal static string AuthorEmailAddressIsRequired {
            get {
                return ResourceManager.GetString("AuthorEmailAddressIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        internal static string AuthorNameIsRequired {
            get {
                return ResourceManager.GetString("AuthorNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name length must be less then 71 characters..
        /// </summary>
        internal static string AuthorNameLengthMustBeLessThen71 {
            get {
                return ResourceManager.GetString("AuthorNameLengthMustBeLessThen71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author password is invalid. The password length must be between 6 and 12 characters..
        /// </summary>
        internal static string AuthorPasswordIsInvalid {
            get {
                return ResourceManager.GetString("AuthorPasswordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string AuthorPasswordIsRequired {
            get {
                return ResourceManager.GetString("AuthorPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        internal static string CategoryNameIsRequired {
            get {
                return ResourceManager.GetString("CategoryNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name length must be less then 71 characters..
        /// </summary>
        internal static string CategoryNameLengthMustBeLessThen71 {
            get {
                return ResourceManager.GetString("CategoryNameLengthMustBeLessThen71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment body is required..
        /// </summary>
        internal static string CommentBodyIsRequired {
            get {
                return ResourceManager.GetString("CommentBodyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        internal static string CommentNameIsRequired {
            get {
                return ResourceManager.GetString("CommentNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment PostId is required..
        /// </summary>
        internal static string CommentPostIdIsRequired {
            get {
                return ResourceManager.GetString("CommentPostIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message not set..
        /// </summary>
        internal static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
    }
}
